DROP TABLE IF EXISTS peer;

CREATE TABLE peer(
                      id INT GENERATED BY DEFAULT AS IDENTITY,
                      name VARCHAR(30) NOT NULL ,
                      age INT NOT NULL,
                      email VARCHAR UNIQUE NOT NULL ,
                      address VARCHAR NOT NULL
);

INSERT INTO peer(name, age, email, address)
VALUES ('Tom', 22, 'tom@mail.ru', 'Moscow, Volkova, 22'),
       ('Bob', 14, 'bob@mail.ru', 'Kazan, Volkova, 24'),
       ('Mike', 67, 'mike@mail.ru', 'Sochi, Volkova, 24'),
       ('Katy', 43, 'katy@mail.ru', 'New York, Volkova, 24');