version: '3'

services:

  nginx:
    build: ./nginx
    restart: always
    links:
      - tomcat
    ports:
      - '8080:8080'
    depends_on:
      - tomcat
  tomcat:
    build: ./tomcat
    restart: always
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres